services:
  kkos2.subscriber.ColorfulMessageSisCron:
    class: Kkos2\KkOs2DisplayIntegrationBundle\Cron\ColorfulMessageSisCron
    arguments: [@service_container]
    tags:
      - { name: kernel.event_subscriber }
