services:
  _defaults:
    autowire: true
  kkos2.subscriber.colorfulMessageSisCron:
    class: Kkos2\KkOs2DisplayIntegrationBundle\Cron\ColorfulMessageSisCron
    tags:
      - { name: kernel.event_subscriber }
  kkos2.subscriber.eventplakatSisCron:
    class: Kkos2\KkOs2DisplayIntegrationBundle\Cron\EventplakatSisCron
    tags:
      - { name: kernel.event_subscriber }
  kkos2.subscriber.eventsSisCron:
    class: Kkos2\KkOs2DisplayIntegrationBundle\Cron\EventsSisCron
    tags:
      - { name: kernel.event_subscriber }
