parameters:
#    indholdskanalen_main.example.class: Indholdskanalen\MainBundle\Example

services:
#    indholdskanalen_main.example:
#        class: %indholdskanalen_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  indholdskanalen_main.listener:
    class: Indholdskanalen\MainBundle\EventListener\SearchIndexer
    arguments: [@jms_serializer]
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: preRemove }

  indholdskanalen_main.serialization_listener:
      class: Indholdskanalen\MainBundle\EventListener\SerializationListener
      arguments: [@sonata.media.pool]
      tags:
        - { name: jms_serializer.event_subscriber}


  #indholdskanalen_main.serializer.handler.image_handler:
  #    class: Indholdskanalen\MainBundle\EventListener\ImageSerializationHandler
  #    arguments: []
  #    tags:
  #        - { name: "jms_serializer.handler", type: \Application\Sonata\MediaBundle\Entity\Media, format: json, method: serialize }