parameters:
#    indholdskanalen_main.example.class: Indholdskanalen\MainBundle\Example

services:
#    indholdskanalen_main.example:
#        class: %indholdskanalen_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  indholdskanalen_main.listener:
    class: Indholdskanalen\MainBundle\EventListener\SearchIndexer
    arguments: [@jms_serializer]
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: PreRemove }
