parameters:
#    indholdskanalen_main.example.class: Indholdskanalen\MainBundle\Example

services:
#    indholdskanalen_main.example:
#        class: %indholdskanalen_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
