jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            SonataMediaBundle:
                namespace_prefix: "Sonata\\MediaBundle"
                path: "@Os2DisplayMediaBundle/Resources/config/serializer/SonataMedia"
