sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                landscape: { width: 960 }
                portrait: { height: 540 }
                landscape_small: { width: 300 }
                portrait_small: { height: 150 }
    cdn:
        server:
            path: '%absolute_path_to_server%/uploads/media'
    filesystem:
        local:
            directory:  '%kernel.root_dir%/../web/uploads/media'
            create:     false
    class:
        media: Os2Display\MediaBundle\Entity\Media
        gallery: Os2Display\MediaBundle\Entity\Gallery
        gallery_has_media: Os2Display\MediaBundle\Entity\GalleryHasMedia
