assets:
  js_prod:
    - bundles/kkbding2integration/assets/build/kkbding2integration.min.js

modules:
  dingTools:
    files:
      - bundles/kkbding2integration/apps/dingEditors/background-editor-static-colors.js
      - bundles/kkbding2integration/apps/dingEditors/ding-events-editor.js
      - bundles/kkbding2integration/apps/dingEditors/opening-hours-editor.js
      - bundles/kkbding2integration/apps/dingEditors/text-color-editor.js
      - bundles/kkbding2integration/apps/dingEditors/header-editor.js
      - bundles/kkbding2integration/apps/dingEditors/info-editor.js
      - bundles/kkbding2integration/apps/dingEditors/image-picker.js
      - bundles/kkbding2integration/apps/dingEditors/logo-picker.js
      - bundles/kkbding2integration/apps/dingEditors/reference-editor.js

apps:
