parameters:
  apps:
    mainApp:
      files:
        - /apps/mainApp/services/userFactory.js
      dependencies:
        - logModule

    menuApp:
      files:
        - /apps/menuApp/menuController.js
      template: /apps/menuApp/menu.html
      dependencies:
        - busModule
        - mainApp

    messageApp:
      files:
        - /apps/messageApp/directive/messagesDirective.js
      template: /apps/messageApp/message.html
      dependencies:
        - busModule