parameters:
  apps:
    mainApp:
      files:
        - /apps/mainApp/mainController.js
        - /apps/mainApp/services/userFactory.js
      dependencies:
        - busApp

    logApp:
      files:
        - /apps/logApp/logModule.js
      dependencies:
        - busApp

    menuApp:
      files:
        - /apps/menuApp/menuController.js
      template: /apps/menuApp/menu.html
      dependencies:
        - busApp
        - mainApp
        - logApp