parameters:
  apps:
    mainApp:
      files:
        - /apps/mainApp/mainController.js
        - /apps/mainApp/services/userFactory.js
      dependencies:
        - busModule

    menuApp:
      files:
        - /apps/menuApp/menuController.js
      template: /apps/menuApp/menu.html
      dependencies:
        - busModule
        - logModule
        - mainApp
