parameters:
  apps:
    menuApp:
      files:
        - /apps/menuApp/menuController.js
      template: /apps/menuApp/menu.html
      controller: MenuController
      dependencies:
        - busModule
        - mainModule

    messageApp:
      files:
        - /apps/messageApp/directive/messagesDirective.js
      template: /apps/messageApp/message.html
      dependencies:
        - busModule
        - mainModule