imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: '%debug_toolbar%'
    intercept_redirects: '%debug_redirects%'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
        nested:
            type: stream
            path: "/tmp/stdout"
            level: info
        console:
            type: console
            bubble: false
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']

swiftmailer:
    transport: smtp
    host:      127.0.0.1
    username:  null
    password:  null
    port: 1025
    spool:     { type: memory }
