imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
        nested:
            type: stream
            path: "/tmp/stdout"
            level: info
            formatter: Monolog\Formatter\JsonFormatter
        console:
            type: console
            bubble: false
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
            formatter: Monolog\Formatter\JsonFormatter
