imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ['zencoder']
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        zencoder:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.zencoder.log"
            level:  debug
            channels: [zencoder]
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type:   console
            bubble: false
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

swiftmailer:
    transport: smtp
    host:      127.0.0.1
    username:  null
    password:  null
    port: 1025
    spool:     { type: memory }
