imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: apps.yml }
  - { resource: modules.yml }

framework:
  #esi:             ~
  translator:      { fallback: "%locale%" }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
    #assets_version: SomeVersionScheme
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
    cookie_lifetime: 0
  fragments:       ~
  http_method_override: true

# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    sharing_host: %sharing_host%
    sharing_enabled: %sharing_enabled%
    search_host: %search_host%
    search_index: %search_index%
    site_title: %site_title%
    version: %version%
    itk_log_version: %itk_log_version%
    itk_log_error_callback: %itk_log_error_callback%
    itk_log_log_to_console: %itk_log_log_to_console%
    itk_log_log_level: %itk_log_log_level%
    apps: %apps%
    modules: %modules%
    bootstrap: %bootstrap%


# Assetic Configuration
assetic:
  debug:          "%kernel.debug%"
  use_controller: false
  bundles:        [ ]
  #java: /usr/bin/java
  filters:
    cssrewrite: ~
    #closure:
    #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
    #yui_css:
    #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
  dbal:
    driver:   "%database_driver%"
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8
    # if using pdo_sqlite as your database driver, add the path in parameters.yml
    # e.g. database_path: "%kernel.root_dir%/data/data.db3"
    # path:     "%database_path%"
    types:
      json: Sonata\Doctrine\Types\JsonType

  orm:
      auto_generate_proxy_classes: %kernel.debug%
      auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  password:  "%mailer_password%"
  spool:     { type: memory }

sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:   [admin]
    sonata.user.block.menu:    # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes

fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: Application\Sonata\UserBundle\Entity\User

  group:
    group_class:   Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager

  service:
    user_manager: sonata.user.orm.user_manager

  from_email:
      address:        "%mailer_from_email%"
      sender_name:    "%mailer_from_name%"

sonata_media:
  # if you don't use default namespace configuration
  #class:
  #    media: MyVendor\MediaBundle\Entity\Media
  #    gallery: MyVendor\MediaBundle\Entity\Gallery
  #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
  default_context: default
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
  contexts:
    default:  # the default context is mandatory
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file

      formats:
        landscape: { width: 960 }
        portrait: { height: 540 }
        landscape_small: { width: 300 }
        portrait_small: { height: 150 }

  cdn:
    server:
      path: %absolute_path_to_server%/uploads/media

  filesystem:
    local:
      directory:  %kernel.root_dir%/../web/uploads/media
      create:     false

sonata_user:
  security_acl: true
  manager_type: orm # can be orm or mongodb

jms_serializer:
  metadata:
    auto_detection: true
    directories:
      SonataMediaBundle:
        namespace_prefix: "Sonata\\MediaBundle"
        path: "@ApplicationSonataMediaBundle/Resources/config/serializer/SonataMedia"
      SonataUserBundle:
        namespace_prefix: "Sonata\\UserBundle"
        path: "@ApplicationSonataUserBundle/Resources/config/serializer/SonataUser"
      FOSUserBundle:
        namespace_prefix: "FOS\\UserBundle"
        path: "@ApplicationSonataUserBundle/Resources/config/serializer/FOSUser"