parameters:
  modules:
    busModule:
      files:
        - /apps/busModule/busModule.js
      dependencies:

    logModule:
      files:
        - /apps/logModule/services/logService.js
        - /apps/logModule/directive/logDirective.js
      dependencies:
        - busModule

  bootstrap:
    - logService