parameters:
  modules:
    busModule:
      files:
        - /apps/busModule/busModule.js
      dependencies:

    logModule:
      files:
        - /apps/logModule/services/logService.js
      dependencies:
        - busModule

  bootstrap:
    modules:
      - logModule
      - mainApp
    services:
      - logService
      - menuItemService