parameters:
  modules: []

  bootstrap:
    modules:
      - logModule
      - mainModule
    services:
      - apiService
      - logService
      - userService
      - searchService
      - menuItemService
      - bodyService
      - authHttpResponseInterceptor
