modules:
  toolsModule:
    files:
      - bundles/os2displaydefaulttemplate/apps/toolsModule/background-editor-static-colors.js
      - bundles/os2displaydefaulttemplate/apps/toolsModule/background-editor-transparent.js
apps:
