services:
  kkb.ding2_service:
    class: Kkb\Ding2IntegrationBundle\Service\Ding2Service
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron }
